//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vw_CustomerOverView
    {
        public string 客戶名稱 { get; set; }
        [Display(Name ="銀行帳戶數量")]
        public Nullable<int> BankTotal { get; set; }
        [Display(Name = "聯絡人數量")]
        public Nullable<int> ContactTotal { get; set; }
    }
}
