//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "欄位長度不得超過30字元")]
        public string 職稱 { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "欄位長度不得超過30字元")]
        public string 姓名 { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage ="請輸入正確信箱格式")]
        public string Email { get; set; }
        [Required]
        [RegularExpression(@"\d{4}-\d{6}", ErrorMessage ="電話格式錯誤;請依照以下格式:09xx-xxxxxx")]
        public string 手機 { get; set; }
        public string 電話 { get; set; }
        public bool Is刪除 { get; set; }
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
