//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class 客戶資料:IValidatableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 客戶資料()
        {
            this.客戶銀行資訊 = new HashSet<客戶銀行資訊>();
            this.客戶聯絡人 = new HashSet<客戶聯絡人>();
        }
    
        public int Id { get; set; }
        [Required]
        [StringLength(30, ErrorMessage = "欄位長度不得超過30字元")]
        public string 客戶名稱 { get; set; }
        [Required]
        public string 統一編號 { get; set; }
        [Required]
        [RegularExpression(@"\d{4}-\d{6}", ErrorMessage = "電話格式錯誤;請依照以下格式:09xx-xxxxxx")]
        public string 電話 { get; set; }
        public string 傳真 { get; set; }
        public string 地址 { get; set; }
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "請輸入正確信箱格式")]
        public string Email { get; set; }
        public bool Is刪除 { get; set; }
        public string 帳號 { get; set; }
        public string 密碼 { get; set; }
        public string 客戶分類 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶銀行資訊> 客戶銀行資訊 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<客戶聯絡人> 客戶聯絡人 { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (this.統一編號.Length != 8)
            {
                yield return new ValidationResult("統一編號請輸入8位數", new string[] { "統一編號" });
            }
            yield break;
        }
    }
}
